server:
  port: 18881
  ui_port: 7860
  ui_share: false
cache:
  node:
    fields:
      - PersonId
      - name
      - labels
  async: thread
model:
  graph-entity:
    search-key: name
  embedding:
    model-name: iic/nlp_corom_sentence-embedding_chinese-base
    device: cpu

database:
  mysql:
    host: localhost
    port: 3306
    user: root
    password: 123456
    database: test

  neo4j:
    url: bolt://172.16.67.154:7687
    database: neo4j
    username: neo4j
    password: neo4jtoo

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 1

  elasticsearch:
    host: localhost
    port: 9200
    scheme: http
    user: elastic
    password: 123456
    enabled: false

  mongodb:
    uri: mongodb://localhost:27017/
    db: test
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 1

lang-chain:
  audio:
    voice:
      NORMAL-MALE: zh-CN-YunxiNeural # male 正式
      NORMAL-FEMALE: zh-CN-XiaoxiaoNeural # female 正式
            #zh-CN-XiaoyiNeural
            #zh-CN-YunjianNeural
            #zh-CN-YunxiNeural
            #zh-CN-YunxiaNeural
            #zh-CN-YunyangNeural
      DONGBEI-FEMALE: zh-CN-liaoning-XiaobeiNeural
      SHANXI-FEMALE: zh-CN-shaanxi-XiaoniNeural
      HK-FEMALE: zh-HK-HiuGaaiNeural
            #zh-HK-HiuMaanNeural
      HK-MALE: zh-HK-WanLungNeural
      TW-FEMALE: zh-TW-HsiaoChenNeural
            #zh-TW-HsiaoYuNeural
      TW-MALE: zh-TW-YunJheNeural


api:
  title: '  "遇见李白" created by Nong Bin' # 必须使用单引号
  description: 'knowledge graph ang chatbot for chinese ancient poets and other cultures'
log:
  level: INFO

ip:
  valid:
    prefix:
      - 10.100
      - 172.16
      - 127.0
